name: AutoChecker

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout github repo with lfs
        uses: actions/checkout@v2
        with:
          lfs: true
      - name: Checkout LFS object
        run: git lfs checkout
      - name: Set up Python 3.6
        uses: actions/setup-python@v1
        with:
          python-version: 3.6
      - name: Install dependencies
        run: |
          pip install -r assets/requirements.txt
      - name: Test with pytest
        run: |
          pytest -vv
